version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    network_mode: "host"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=KienPassword123!
      - MSSQL_PID=Developer
      - MSSQL_NETWORK_RPCPORT=135
      - MSSQL_DISTRIBUTEDTRANSACTION_TURNOFFRPCSECURITY=1
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqldata: